# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issues.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User')),
            ],
        ),
    ]
