# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timelog_issue', to='issues.Issue', verbose_name='issue'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timelog_user', to='users.User', verbose_name='user'),
        ),
    ]
