# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0002_auto_20170627_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='timelog comment'),
        ),
    ]
