# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170525_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified date'),
        ),
    ]
