# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170607_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modified_date',
            field=models.DateTimeField(null=True, verbose_name='modified date'),
        ),
    ]
