# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170607_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.Role'),
        ),
    ]
