# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170622_0902'),
        ('projects', '0012_auto_20170608_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masquerade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masque', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='masque', to='users.User')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', 'id'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='masquerade',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masquerades', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='masquerade',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='masques',
            field=models.ManyToManyField(blank=True, related_name='masque_projects', through='projects.Masquerade', to='users.User', verbose_name='masques'),
        ),
    ]
