# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 13:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20170626_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
