PERMISSIONS = [
    ('admin.add_logentry', 'Can add log entry'),
    ('admin.change_logentry', 'Can change log entry'),
    ('admin.delete_logentry', 'Can delete log entry'),
    ('auth.add_user', 'Can add user'),
    ('auth.change_user', 'Can change user'),
    ('auth.delete_user', 'Can delete user'),
    ('auth.add_group', 'Can add group'),
    ('auth.change_group', 'Can change group'),
    ('auth.delete_group', 'Can delete group'),
    ('auth.add_permission', 'Can add permission'),
    ('auth.change_permission', 'Can change permission'),
    ('auth.delete_permission', 'Can delete permission'),
    ('contenttypes.add_contenttype', 'Can add content type'),
    ('contenttypes.change_contenttype', 'Can change content type'),
    ('contenttypes.delete_contenttype', 'Can delete content type'),
    ('sessions.add_session', 'Can add session'),
    ('sessions.change_session', 'Can change session'),
    ('sessions.delete_session', 'Can delete session'),
    ('users.add_user', 'Can add user'),
    ('users.change_user', 'Can change user'),
    ('users.delete_user', 'Can delete user'),
    ('projects.add_project', 'Can add project'),
    ('projects.change_project', 'Can change project'),
    ('projects.delete_project', 'Can delete project'),
    ('issues.add_issue', 'Can add issue'),
    ('issues.change_issue', 'Can change issue'),
    ('issues.delete_issue', 'Can delete issue'),
    ('wiki.add_wiki', 'Can add wiki'),
    ('wiki.change_wiki', 'Can change wiki'),
    ('wiki.delete_wiki', 'Can delete wiki'),
    ('wiki.add_wiki', 'Can add wiki'),
    ('wiki.change_wiki', 'Can change wiki'),
    ('wiki.delete_wiki', 'Can delete wiki'),
]


ADMIN_PERMISSIONS = [
    'admin.add_logentry',
    'admin.change_logentry',
    'admin.delete_logentry',
    'auth.add_user',
    'auth.change_user',
    'auth.delete_user',
    'auth.add_group',
    'auth.change_group',
    'auth.delete_group',
    'auth.add_permission',
    'auth.change_permission',
    'auth.delete_permission',
    'contenttypes.add_contenttype',
    'contenttypes.change_contenttype',
    'contenttypes.delete_contenttype',
    'sessions.add_session',
    'sessions.change_session',
    'sessions.delete_session',
    'users.add_user',
    'users.change_user',
    'users.delete_user',
    'projects.add_project',
    'projects.change_project',
    'projects.delete_project',
    'issues.add_issue',
    'issues.change_issue',
    'issues.delete_issue',
    'timelogs.add_timelog',
    'timelogs.change_timelog',
    'timelogs.delete_timelog',
    'wiki.add_wiki',
    'wiki.change_wiki',
    'wiki.delete_wiki',
]

DEVELOPER_PERMISSIONS = [
    'contenttypes.add_contenttype',
    'contenttypes.change_contenttype',
    'contenttypes.delete_contenttype',
    'sessions.add_session',
    'sessions.change_session',
    'sessions.delete_session',
    'users.add_user',
    'users.change_user',
    'users.delete_user',
    'projects.add_project',
    'projects.change_project',
    'projects.delete_project',
    'issues.add_issue',
    'issues.change_issue',
    'issues.delete_issue',
    'timelogs.add_timelog',
    'timelogs.change_timelog',
    'timelogs.delete_timelog',
    'wiki.add_wiki',
    'wiki.change_wiki',
    'wiki.delete_wiki',
]

REPORTER_PERMISSIONS = [
    'issues.add_issue',
    'issues.change_issue',
    'issues.delete_issue',
    'timelogs.add_timelog',
    'timelogs.change_timelog',
    'timelogs.delete_timelog',
    'wiki.add_wiki',
    'wiki.change_wiki',
    'wiki.delete_wiki',
]