# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='myfield',
            new_name='text',
        ),
    ]
