# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20170615_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
