# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170615_1028'),
        ('projects', '0012_auto_20170608_1400'),
        ('wiki', '0004_auto_20170615_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiki',
            options={'ordering': ['project'], 'verbose_name': 'wiki page', 'verbose_name_plural': 'wiki pages'},
        ),
        migrations.RenameField(
            model_name='wiki',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='wiki',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wiki',
            name='last_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_wiki_pages', to='users.User', verbose_name='last modifier'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified_date'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_wiki_pages', to='users.User', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='projects.Project'),
            preserve_default=False,
        ),
    ]
