# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 08:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170616_0836'),
        ('wiki', '0006_auto_20170619_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=[], null=True, size=None, verbose_name='wiki_permissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.AlterModelOptions(
            name='wiki',
            options={'ordering': ['project'], 'permissions': (('view_wiki', 'Can view wiki page'),), 'verbose_name': 'wiki page', 'verbose_name_plural': 'wiki pages'},
        ),
        migrations.AddField(
            model_name='wiki',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_parents', to='wiki.Wiki'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='last_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_wiki_pages', to='users.User', verbose_name='last_modifier'),
        ),
        migrations.AddField(
            model_name='wikipermissions',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Wiki'),
        ),
    ]
