# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20170619_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='wikipermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_permissions', to='users.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='wikipermissions',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_permissions', to='wiki.Wiki', verbose_name='wiki page'),
        ),
    ]
