# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 13:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170525_1331'),
        ('users', '0002_auto_20170525_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('admin.add_logentry', 'Can add log entry'), ('admin.change_logentry', 'Can change log entry'), ('admin.delete_logentry', 'Can delete log entry'), ('auth.add_user', 'Can add user'), ('auth.change_user', 'Can change user'), ('auth.delete_user', 'Can delete user'), ('auth.add_group', 'Can add group'), ('auth.change_group', 'Can change group'), ('auth.delete_group', 'Can delete group'), ('auth.add_permission', 'Can add permission'), ('auth.change_permission', 'Can change permission'), ('auth.delete_permission', 'Can delete permission'), ('contenttypes.add_contenttype', 'Can add content type'), ('contenttypes.change_contenttype', 'Can change content type'), ('contenttypes.delete_contenttype', 'Can delete content type'), ('sessions.add_session', 'Can add session'), ('sessions.change_session', 'Can change session'), ('sessions.delete_session', 'Can delete session'), ('users.add_user', 'Can add user'), ('users.change_user', 'Can change user'), ('users.delete_user', 'Can delete user'), ('projects.add_project', 'Can add project'), ('projects.change_project', 'Can change project'), ('projects.delete_project', 'Can delete project'), ('issues.add_issue', 'Can add issue'), ('issues.change_issue', 'Can change issue'), ('issues.delete_issue', 'Can delete issue'), ('timelogs.add_timelog', 'Can add timelog'), ('timelogs.change_timelog', 'Can change timelog'), ('timelogs.delete_timelog', 'Can delete timelog')]), blank=True, default=[], null=True, size=None, verbose_name='permissions')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.Project', verbose_name='project')),
            ],
        ),
    ]
