# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='project',
        ),
    ]
