# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 08:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170615_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('admin.add_logentry', 'Can add log entry'), ('admin.change_logentry', 'Can change log entry'), ('admin.delete_logentry', 'Can delete log entry'), ('auth.add_user', 'Can add user'), ('auth.change_user', 'Can change user'), ('auth.delete_user', 'Can delete user'), ('auth.add_group', 'Can add group'), ('auth.change_group', 'Can change group'), ('auth.delete_group', 'Can delete group'), ('auth.add_permission', 'Can add permission'), ('auth.change_permission', 'Can change permission'), ('auth.delete_permission', 'Can delete permission'), ('contenttypes.add_contenttype', 'Can add content type'), ('contenttypes.change_contenttype', 'Can change content type'), ('contenttypes.delete_contenttype', 'Can delete content type'), ('sessions.add_session', 'Can add session'), ('sessions.change_session', 'Can change session'), ('sessions.delete_session', 'Can delete session'), ('wiki.add_user', 'Can add user'), ('wiki.change_user', 'Can change user'), ('wiki.delete_user', 'Can delete user'), ('projects.add_project', 'Can add project'), ('projects.change_project', 'Can change project'), ('projects.delete_project', 'Can delete project'), ('issues.add_issue', 'Can add issue'), ('issues.change_issue', 'Can change issue'), ('issues.delete_issue', 'Can delete issue'), ('wiki.add_wiki', 'Can add wiki'), ('wiki.change_wiki', 'Can change wiki'), ('wiki.delete_wiki', 'Can delete wiki'), ('wiki.add_wiki', 'Can add wiki'), ('wiki.change_wiki', 'Can change wiki'), ('wiki.delete_wiki', 'Can delete wiki')]), blank=True, default=[], null=True, size=None, verbose_name='permissions'),
        ),
    ]
