# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
