# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='user',
            field=models.IntegerField(),
        ),
    ]
