# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 12:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170627_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='mngr',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
