# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('feedback', 'Feedback'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='new', max_length=16),
        ),
    ]
