# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20170607_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified date'),
        ),
    ]
