# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20170608_1400'),
        ('users', '0008_auto_20170622_0902'),
        ('issues', '0008_auto_20170622_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.IntegerField(default=10, verbose_name='order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name_plural': 'issue priorities',
                'verbose_name': 'issue priority',
                'ordering': ['project', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='issue_users', to='users.User', verbose_name='issue users'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_issues', to='users.User', verbose_name='assigned_to'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('feedback', 'Feedback'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='issue status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='issue subject'),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues.IssuePriority', verbose_name='issue priority'),
        ),
        migrations.AlterUniqueTogether(
            name='issuepriority',
            unique_together=set([('project', 'name')]),
        ),
    ]
