# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20170626_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssuePriority',
            new_name='Priority',
        ),
    ]
