# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20170626_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='priority',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='priority',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='priority',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
