# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20170626_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 1), ('normal', 2), ('high', 3)], default='normal', max_length=10, verbose_name='issue priority'),
        ),
    ]
