# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_issue_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 1), ('in_progress', 2), ('resolved', 3), ('feedback', 4), ('rejected', 5), ('closed', 6)], default='new', max_length=20, verbose_name='issue status'),
        ),
    ]
