# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_auto_20170626_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('order', models.IntegerField(default=10, verbose_name='order')),
            ],
            options={
                'verbose_name_plural': 'priorities',
                'ordering': ['order', 'name'],
                'verbose_name': 'priority',
            },
        ),
        migrations.RemoveField(
            model_name='issue',
            name='priority',
        ),
    ]
