# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_auto_20170626_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues.Priority', verbose_name='issue status'),
            preserve_default=False,
        ),
    ]
