# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_remove_status_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(max_length=20, verbose_name='issue status'),
        ),
    ]
