# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0020_auto_20170626_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues.Status', verbose_name='issue status'),
        ),
    ]
