# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0022_testus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order', 'name'], 'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
    ]
