# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0023_auto_20170627_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testus',
        ),
    ]
