# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0024_delete_testus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to='users.User', verbose_name='assigned_to'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='issues', to='users.User', verbose_name='issue users'),
        ),
    ]
