# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0025_auto_20170627_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_issues', to='users.User', verbose_name='assigned_to'),
        ),
    ]
